version: '3.9'
services:
    wiremock:
      image: wiremock/wiremock:latest
      ports:
      - '8880:8080'
      volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
      command:
      - -verbose
     
        
        