server:
   port: 8081
spring:
   jmx:
      enabled: false
   servlet:
      multipart:
         enabled: true
         max-request-size: 10MB
         max-file-size: 10MB
         location: ${java.io.tmpdir}

gallery-host:
   artist: http://${DOCKER_HOST}:8880/artist/
   artwork: http://${DOCKER_HOST}:8880/artwork/
   transaction: http://${DOCKER_HOST}:8880/transaction/